// ============================================================
// Axon — SummaryDetailView (Professor: full-page editor)
//
// Full-page editor experience. The TipTap editor fills the
// entire available space. Keywords and Videos are accessible
// from toolbar buttons that open right-side sheets.
// Chunks are auto-generated by the backend — no UI needed.
// ============================================================
import React, { useState, useCallback, useMemo, Suspense } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { toast } from 'sonner';
import {
  Plus, Edit3, Trash2, Save, X, Loader2,
  RotateCcw, ChevronDown, ChevronUp, Tag,
  Video as VideoIcon, Layers,
} from 'lucide-react';
import { Button } from '@/app/components/ui/button';
import { Input } from '@/app/components/ui/input';
import { Textarea } from '@/app/components/ui/textarea';
import { Skeleton } from '@/app/components/ui/skeleton';
import {
  Sheet, SheetContent, SheetHeader, SheetTitle,
} from '@/app/components/ui/sheet';
import { ConfirmDialog } from '@/app/components/shared/ConfirmDialog';
import { useQuery } from '@tanstack/react-query';
import { queryKeys } from '@/app/hooks/queries/queryKeys';
import { PROFESSOR_CONTENT_STALE } from '@/app/hooks/queries/staleTimes';
import {
  useCreateKeywordMutation,
  useUpdateKeywordMutation,
  useDeleteKeywordMutation,
  useRestoreKeywordMutation,
} from '@/app/hooks/queries/useKeywordsManagerQueries';
import {
  useCreateSubtopicMutation,
  useDeleteSubtopicMutation,
} from '@/app/hooks/queries/useSubtopicMutations';
import * as api from '@/app/services/summariesApi';
import type { Summary, SummaryKeyword, SummaryBlock, Subtopic } from '@/app/services/summariesApi';
import { VideosManager } from '@/app/components/professor/VideosManager';
import { TipTapEditor } from '@/app/components/tiptap/TipTapEditor';
import {
  useQuickKeywordCreator,
  QuickKeywordFormPortal,
} from '@/app/components/professor/QuickKeywordCreator';
import { KeywordClickPopover } from '@/app/components/professor/KeywordClickPopover';
import { extractItems } from '@/app/lib/api-helpers';
import BlockEditor from '@/app/components/professor/block-editor/BlockEditor';
import { ErrorBoundary } from '@/app/components/shared/ErrorBoundary';

// ── Keyword list priority config (module-scope — no per-render/per-item allocation) ──
const KW_PRIORITY_CONFIG: Record<number, { border: string; dot: string; label: string }> = {
  0: { border: 'border-l-gray-200', dot: 'bg-gray-300', label: '' },
  1: { border: 'border-l-emerald-400', dot: 'bg-emerald-400', label: 'Baja' },
  2: { border: 'border-l-amber-400', dot: 'bg-amber-400', label: 'Media' },
  3: { border: 'border-l-red-400', dot: 'bg-red-400', label: 'Alta' },
};

// ── Priority selector options (shared between create & edit forms) ──
const PRIORITY_OPTIONS = [
  { value: 1, label: 'Baja', active: 'bg-emerald-50 border-emerald-300 text-emerald-700', idle: 'bg-white border-gray-200 text-gray-400', dot: 'bg-emerald-400' },
  { value: 2, label: 'Media', active: 'bg-amber-50 border-amber-300 text-amber-700', idle: 'bg-white border-gray-200 text-gray-400', dot: 'bg-amber-400' },
  { value: 3, label: 'Alta', active: 'bg-red-50 border-red-300 text-red-700', idle: 'bg-white border-gray-200 text-gray-400', dot: 'bg-red-400' },
] as const;

// ── Props ─────────────────────────────────────────────────

interface SummaryDetailViewProps {
  summary: Summary;
  topicName: string;
  onBack: () => void;
  onSummaryUpdated: () => void;
}

export function SummaryDetailView({
  summary,
  topicName,
  onBack,
  onSummaryUpdated,
}: SummaryDetailViewProps) {
  // ── Editor mode: 'blocks' when summary has blocks, 'tiptap' otherwise ──
  const [editorMode, setEditorMode] = useState<'blocks' | 'tiptap' | null>(null);

  // ── Sheet state ─────────────────────────────────────────
  const [showKeywords, setShowKeywords] = useState(false);
  const [showVideos, setShowVideos] = useState(false);

  // ── Keywords (React Query — shared cache, ALL keywords) ──
  const { data: allKeywords = [], isLoading: keywordsLoading } = useQuery({
    queryKey: queryKeys.summaryKeywords(summary.id),
    queryFn: async () => {
      const result = await api.getKeywords(summary.id);
      return extractItems<SummaryKeyword>(result);
    },
    staleTime: PROFESSOR_CONTENT_STALE,
  });

  // ── Keyword mutations ──────────────────────────────────
  const createMutation = useCreateKeywordMutation(summary.id);
  const updateMutation = useUpdateKeywordMutation(summary.id);
  const deleteMutation = useDeleteKeywordMutation(summary.id);
  const restoreMutation = useRestoreKeywordMutation(summary.id);

  // ── Keyword form state (local UI only) ─────────────────
  const [showNewKeyword, setShowNewKeyword] = useState(false);
  const [newKeywordName, setNewKeywordName] = useState('');
  const [newKeywordDef, setNewKeywordDef] = useState('');
  const [newKeywordPriority, setNewKeywordPriority] = useState<number>(0);
  const [editingKeywordId, setEditingKeywordId] = useState<string | null>(null);
  const [editKwName, setEditKwName] = useState('');
  const [editKwDef, setEditKwDef] = useState('');
  const [editKwPriority, setEditKwPriority] = useState<number>(0);
  const [deletingKeywordId, setDeletingKeywordId] = useState<string | null>(null);

  // ── Derived keyword views ──────────────────────────────
  const activeKeywords = useMemo(() => allKeywords.filter(k => k.is_active), [allKeywords]);
  const activeKeywordNames = useMemo(() => activeKeywords.map(k => k.name), [activeKeywords]);

  // Subtopics per keyword (expanded)
  const [expandedKeyword, setExpandedKeyword] = useState<string | null>(null);
  const [newSubtopicName, setNewSubtopicName] = useState('');

  // ── Subtopics query (React Query — on-demand per expanded keyword) ──
  // Professor sees ALL subtopics (including inactive) for management.
  // Cache key: kwSubtopics(keywordId). Previous expansions stay in gcTime.
  const { data: currentSubtopics = [], isLoading: subtopicsLoading } = useQuery({
    queryKey: queryKeys.kwSubtopics(expandedKeyword!),
    queryFn: async () => {
      const result = await api.getSubtopics(expandedKeyword!);
      // NO is_active filter — professor sees ALL for management
      return extractItems<Subtopic>(result)
        .sort((a, b) => (a.order_index ?? 0) - (b.order_index ?? 0));
    },
    enabled: !!expandedKeyword,
    staleTime: PROFESSOR_CONTENT_STALE,
  });

  // ── Subtopic mutations ─────────────────────────────────
  const createSubtopicMutation = useCreateSubtopicMutation(summary.id);
  const deleteSubtopicMutation = useDeleteSubtopicMutation(summary.id);

  // ── Videos count (for toolbar badge) ────────────────────
  const [videosCount, setVideosCount] = useState(0);

  // ── Blocks detection (React Query — shared cache with SummaryViewer) ──
  const { data: hasBlocks = false } = useQuery({
    queryKey: queryKeys.summaryBlocks(summary.id),
    queryFn: async () => {
      const result = await api.getSummaryBlocks(summary.id);
      return extractItems<SummaryBlock>(result)
        .filter(b => b.is_active !== false)
        .sort((a, b) => (a.order_index ?? 0) - (b.order_index ?? 0));
    },
    staleTime: PROFESSOR_CONTENT_STALE,
    select: (blocks) => blocks.length > 0,
  });

  // ── Auto-detect editor mode based on blocks presence ─────
  // Once query resolves, set mode if not yet chosen by user.
  const resolvedMode = editorMode ?? (hasBlocks ? 'blocks' : 'tiptap');

  // ── Quick keyword creator from text selection ───────────
  const quickKw = useQuickKeywordCreator();

  // ── Keyword click popover state ─────────────────────────
  const [clickedKeyword, setClickedKeyword] = useState<SummaryKeyword | null>(null);
  const [clickedKeywordEl, setClickedKeywordEl] = useState<HTMLElement | null>(null);

  const handleKeywordClick = useCallback((kwName: string, anchorEl: HTMLElement) => {
    const kw = allKeywords.find(
      k => k.name.toLowerCase() === kwName.toLowerCase() && k.is_active
    );
    if (!kw) return;
    setClickedKeyword(kw);
    setClickedKeywordEl(anchorEl);
  }, [allKeywords]);

  const handlePopoverClose = useCallback(() => {
    setClickedKeyword(null);
    setClickedKeywordEl(null);
  }, []);

  const handlePopoverEdit = useCallback((kw: SummaryKeyword) => {
    setEditingKeywordId(kw.id);
    setEditKwName(kw.name);
    setEditKwDef(kw.definition || '');
    setEditKwPriority(kw.priority);
    setShowKeywords(true);
  }, []);

  // ── Toolbar callbacks (stable refs — state setters are identity-stable) ──
  const handleKeywordsClick = useCallback(() => setShowKeywords(true), []);
  const handleVideosClick = useCallback(() => setShowVideos(true), []);

  // ── Status change handler ───────────────────────────────
  const handleStatusChange = useCallback(async (newStatus: 'draft' | 'published') => {
    try {
      await api.updateSummary(summary.id, { status: newStatus });
      toast.success(newStatus === 'published' ? 'Publicado' : 'Cambiado a borrador');
      onSummaryUpdated();
    } catch (err: any) {
      toast.error(err.message || 'Error al cambiar estado');
    }
  }, [summary.id, onSummaryUpdated]);

  // ── Keyword CRUD ────────────────────────────────────────
  const handleCreateKeyword = () => {
    if (!newKeywordName.trim()) return;
    // Check for duplicate (case-insensitive)
    const isDuplicate = activeKeywords.some(
      k => k.name.toLowerCase() === newKeywordName.trim().toLowerCase()
    );
    if (isDuplicate) {
      toast.error(`La keyword "${newKeywordName.trim()}" ya existe`);
      return;
    }
    createMutation.mutate(
      { name: newKeywordName.trim(), definition: newKeywordDef.trim() || undefined, priority: newKeywordPriority },
      {
        onSuccess: () => {
          setNewKeywordName('');
          setNewKeywordDef('');
          setNewKeywordPriority(0);
          setShowNewKeyword(false);
        },
      },
    );
  };

  const handleUpdateKeyword = (id: string) => {
    if (!editKwName.trim()) return;
    updateMutation.mutate(
      { keywordId: id, data: { name: editKwName.trim(), definition: editKwDef.trim() || undefined, priority: editKwPriority } },
      {
        onSuccess: () => {
          setEditingKeywordId(null);
        },
      },
    );
  };

  const handleDeleteKeyword = () => {
    if (!deletingKeywordId) return;
    deleteMutation.mutate(deletingKeywordId, {
      onSuccess: () => {
        setDeletingKeywordId(null);
      },
    });
  };

  // ── Subtopic CRUD ───────────────────────────────────────
  const handleCreateSubtopic = (keywordId: string) => {
    if (!newSubtopicName.trim()) return;
    createSubtopicMutation.mutate(
      { keyword_id: keywordId, name: newSubtopicName.trim() },
      {
        onSuccess: () => {
          setNewSubtopicName('');
        },
      },
    );
  };

  const handleDeleteSubtopic = (subtopicId: string, keywordId: string) => {
    deleteSubtopicMutation.mutate({ subtopicId, keywordId });
  };

  // ── Expand keyword to show subtopics ────────────────────
  const toggleKeywordExpand = (keywordId: string) => {
    setExpandedKeyword(prev => prev === keywordId ? null : keywordId);
    setNewSubtopicName(''); // Clear draft when switching keyword expansion
  };

  return (
    <div className="h-full flex flex-col overflow-hidden">
      {/* ══════════════════════════════════════════════════ */}
      {/* EDITOR MODE SWITCH                                */}
      {/* ═══════════════════════════════════════════════════ */}

      {/* Mode toggle banner — always visible in TipTap mode so professor can switch */}
      {resolvedMode === 'tiptap' && (
        <div className="shrink-0 px-4 py-2 bg-gradient-to-r from-teal-50 to-emerald-50 border-b border-teal-100 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] bg-teal-100 text-teal-700 border border-teal-200">
              {hasBlocks ? 'Vista enriquecida disponible' : 'Editor de bloques'}
            </span>
            <button
              onClick={() => setEditorMode('blocks')}
              className="text-[10px] text-teal-600 hover:text-teal-800 underline"
            >
              Cambiar a editor de bloques
            </button>
          </div>
        </div>
      )}

      {resolvedMode === 'blocks' ? (
        /* ── Block Editor (Fase 5) ───────────────────────── */
        <ErrorBoundary fallback={
          <div className="flex flex-col items-center justify-center py-20 text-center">
            <p className="text-sm text-gray-500 font-medium">Error al cargar el editor de bloques</p>
            <button onClick={onBack} className="mt-3 text-xs text-teal-500 hover:underline">Volver</button>
          </div>
        }>
          <BlockEditor
            summaryId={summary.id}
            onBack={onBack}
            onStatusChange={handleStatusChange}
            onKeywordsClick={handleKeywordsClick}
            onVideosClick={handleVideosClick}
            keywordsCount={activeKeywords.length}
            videosCount={videosCount}
            summaryTitle={summary.title || 'Sin titulo'}
            summaryStatus={summary.status}
          />
        </ErrorBoundary>
      ) : (
        /* ── TipTap Editor (legacy) ──────────────────────── */
        <TipTapEditor
          summaryId={summary.id}
          contentMarkdown={summary.content_markdown}
          summaryTitle={summary.title || 'Sin titulo'}
          summaryStatus={summary.status}
          onBack={onBack}
          onStatusChange={handleStatusChange}
          onKeywordsClick={handleKeywordsClick}
          onVideosClick={handleVideosClick}
          keywordsCount={activeKeywords.length}
          videosCount={videosCount}
          onCreateKeywordFromSelection={quickKw.triggerFromEditor}
          keywordNames={activeKeywordNames}
          onKeywordClick={handleKeywordClick}
        />
      )}

      {/* Quick Keyword Creator Portal (from text selection) */}
      <QuickKeywordFormPortal
        state={quickKw.state}
        summaryId={summary.id}
        onClose={quickKw.close}
        existingKeywordNames={activeKeywordNames}
      />

      {/* Keyword Click Popover */}
      {clickedKeyword && clickedKeywordEl && (
        <KeywordClickPopover
          keyword={clickedKeyword}
          allKeywords={activeKeywords}
          anchorEl={clickedKeywordEl}
          onClose={handlePopoverClose}
          onEdit={handlePopoverEdit}
        />
      )}

      {/* ═══════════════════════════════════════════════════ */}
      {/* KEYWORDS SHEET (right side panel)                  */}
      {/* ═══════════════════════════════════════════════════ */}
      <Sheet open={showKeywords} onOpenChange={setShowKeywords}>
        <SheetContent className="w-[460px] sm:max-w-[460px] p-0 flex flex-col h-full overflow-hidden">
          {/* ── Fixed header ─────────────────────────────── */}
          <div className="shrink-0 bg-gradient-to-b from-teal-50/80 to-white px-5 pt-5 pb-3 border-b border-gray-100">
            <SheetHeader className="mb-0">
              <SheetTitle className="flex items-center gap-2.5">
                <div className="w-8 h-8 rounded-xl bg-teal-100 flex items-center justify-center">
                  <Tag size={15} className="text-teal-600" />
                </div>
                <div>
                  <span className="block text-sm text-gray-900" style={{ fontWeight: 600 }}>Palabras clave</span>
                  <span className="text-[10px] text-gray-400" style={{ fontWeight: 400 }}>
                    {activeKeywords.length} activa{activeKeywords.length !== 1 ? 's' : ''}
                    {allKeywords.length > activeKeywords.length && (
                      <> · {allKeywords.length - activeKeywords.length} eliminada{allKeywords.length - activeKeywords.length !== 1 ? 's' : ''}</>
                    )}
                  </span>
                </div>
              </SheetTitle>
            </SheetHeader>

            {/* Tip banner */}
            <div className="mt-3 flex items-start gap-2 bg-teal-50 border border-teal-100 rounded-lg px-3 py-2">
              <Tag size={12} className="text-teal-400 mt-0.5 shrink-0" />
              <p className="text-[11px] text-teal-600/80 leading-relaxed">
                <span style={{ fontWeight: 600 }}>Tip:</span> Selecciona texto en el editor y presiona el boton{' '}
                <span className="inline-flex items-center gap-0.5 bg-[#2a8c7a] text-white px-1.5 py-0 rounded text-[9px]" style={{ fontWeight: 600 }}>
                  <Tag size={8} /> Keyword
                </span>{' '}
                que aparece para crear rapidamente.
              </p>
            </div>

            {/* Add button always visible at top */}
            {!keywordsLoading && (
              <button
                onClick={() => { setShowNewKeyword(true); setEditingKeywordId(null); }}
                className="mt-3 w-full flex items-center justify-center gap-1.5 py-2 rounded-full border-2 border-dashed border-teal-200 text-teal-600 text-xs hover:bg-teal-50 hover:border-teal-300 transition-all active:scale-[0.98]"
                style={{ fontWeight: 600 }}
              >
                <Plus size={13} /> Nueva keyword
              </button>
            )}
          </div>

          {/* ── Scrollable keywords list ─────────────────── */}
          <div className="flex-1 overflow-y-auto px-4 py-3 space-y-2">
            {keywordsLoading ? (
              <div className="space-y-3 pt-2">
                {[1, 2, 3].map(i => (
                  <div key={i} className="rounded-xl border border-gray-100 p-3.5">
                    <div className="flex items-center gap-3">
                      <Skeleton className="w-1 h-8 rounded-full" />
                      <div className="flex-1 space-y-2">
                        <Skeleton className="h-3.5 w-32" />
                        <Skeleton className="h-2.5 w-48" />
                      </div>
                      <Skeleton className="w-6 h-6 rounded-lg" />
                    </div>
                  </div>
                ))}
              </div>
            ) : allKeywords.length === 0 && !showNewKeyword ? (
              <div className="flex flex-col items-center justify-center py-16 text-center">
                <div className="w-14 h-14 rounded-2xl bg-gray-50 border border-gray-100 flex items-center justify-center mb-4">
                  <Tag size={22} className="text-gray-300" />
                </div>
                <p className="text-sm text-gray-500 mb-1" style={{ fontWeight: 500 }}>Sin keywords aun</p>
                <p className="text-xs text-gray-400 max-w-[220px] leading-relaxed">
                  Selecciona texto en el editor o usa el boton de arriba para crear la primera
                </p>
              </div>
            ) : (
              <>
                {/* New keyword form (inline at top) */}
                <AnimatePresence>
                  {showNewKeyword && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      exit={{ opacity: 0, height: 0 }}
                      className="overflow-hidden"
                    >
                      <div className="rounded-xl border-2 border-teal-200 bg-gradient-to-b from-teal-50/50 to-white p-4 space-y-3 mb-2">
                        <div className="flex items-center justify-between">
                          <span className="text-xs text-teal-700" style={{ fontWeight: 600 }}>Nueva keyword</span>
                          <button
                            onClick={() => { setShowNewKeyword(false); setNewKeywordName(''); setNewKeywordDef(''); setNewKeywordPriority(2); }}
                            className="p-1 rounded-md hover:bg-teal-100 text-teal-400 hover:text-teal-600 transition-colors"
                          >
                            <X size={14} />
                          </button>
                        </div>
                        <Input
                          value={newKeywordName}
                          onChange={(e) => setNewKeywordName(e.target.value)}
                          placeholder="Nombre de la keyword..."
                          className="bg-white"
                          autoFocus
                          onKeyDown={(e) => {
                            if (e.key === 'Enter' && !e.shiftKey && newKeywordName.trim()) {
                              e.preventDefault();
                              handleCreateKeyword();
                            }
                          }}
                        />
                        <Textarea
                          value={newKeywordDef}
                          onChange={(e) => setNewKeywordDef(e.target.value)}
                          placeholder="Definicion breve (opcional)"
                          className="min-h-[52px] bg-white resize-none"
                        />
                        <div>
                          <span className="text-[10px] text-gray-500 mb-1.5 block" style={{ fontWeight: 600 }}>Prioridad</span>
                          <div className="flex gap-1.5">
                            {PRIORITY_OPTIONS.map(opt => (
                              <button
                                key={opt.value}
                                type="button"
                                onClick={() => setNewKeywordPriority(opt.value)}
                                className={`flex-1 flex items-center justify-center gap-1.5 px-2 py-2 rounded-lg text-[11px] border transition-all ${
                                  newKeywordPriority === opt.value ? opt.active : opt.idle
                                } hover:border-gray-300`}
                                style={{ fontWeight: newKeywordPriority === opt.value ? 600 : 400 }}
                              >
                                <span className={`w-1.5 h-1.5 rounded-full ${opt.dot}`} />
                                {opt.label}
                              </button>
                            ))}
                          </div>
                        </div>
                        <div className="flex justify-end gap-2 pt-1">
                          <Button
                            size="sm"
                            onClick={handleCreateKeyword}
                            disabled={createMutation.isPending || !newKeywordName.trim()}
                            className="bg-[#2a8c7a] hover:bg-[#244e47] text-white px-5 rounded-full"
                          >
                            {createMutation.isPending ? <Loader2 size={12} className="animate-spin" /> : <Plus size={12} />}
                            Crear keyword
                          </Button>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* Keyword list */}
                {allKeywords.map((kw, idx) => {
                  const pc = KW_PRIORITY_CONFIG[kw.priority] || KW_PRIORITY_CONFIG[0];

                  return (
                    <motion.div
                      key={kw.id}
                      initial={{ opacity: 0, y: 6 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: idx * 0.02 }}
                      className={`rounded-xl border transition-all ${
                        !kw.is_active
                          ? 'border-red-200 bg-red-50/20 opacity-50'
                          : editingKeywordId === kw.id
                            ? 'border-teal-300 bg-teal-50/30 shadow-sm'
                            : 'border-gray-100 hover:border-gray-200 hover:shadow-sm bg-white'
                      } border-l-[3px] ${kw.is_active ? pc.border : 'border-l-red-300'}`}
                    >
                      {editingKeywordId === kw.id ? (
                        /* ── Edit form ───────────────────────────── */
                        <div className="p-3.5 space-y-3">
                          <div className="flex items-center justify-between">
                            <span className="text-xs text-teal-700" style={{ fontWeight: 600 }}>Editando</span>
                            <button
                              onClick={() => setEditingKeywordId(null)}
                              className="p-1 rounded-md hover:bg-gray-100 text-gray-400 hover:text-gray-600 transition-colors"
                            >
                              <X size={14} />
                            </button>
                          </div>
                          <Input
                            value={editKwName}
                            onChange={(e) => setEditKwName(e.target.value)}
                            placeholder="Nombre"
                            autoFocus
                            className="bg-white"
                            onKeyDown={(e) => {
                              if (e.key === 'Enter' && !e.shiftKey && editKwName.trim()) {
                                e.preventDefault();
                                handleUpdateKeyword(kw.id);
                              }
                            }}
                          />
                          <Textarea
                            value={editKwDef}
                            onChange={(e) => setEditKwDef(e.target.value)}
                            placeholder="Definicion (opcional)"
                            className="min-h-[52px] bg-white resize-none"
                          />
                          <div>
                            <span className="text-[10px] text-gray-500 mb-1.5 block" style={{ fontWeight: 600 }}>Prioridad</span>
                            <div className="flex gap-1.5">
                              {PRIORITY_OPTIONS.map(opt => (
                                <button
                                  key={opt.value}
                                  type="button"
                                  onClick={() => setEditKwPriority(opt.value)}
                                  className={`flex-1 flex items-center justify-center gap-1.5 px-2 py-2 rounded-lg text-[11px] border transition-all ${
                                    editKwPriority === opt.value ? opt.active : opt.idle
                                  } hover:border-gray-300`}
                                  style={{ fontWeight: editKwPriority === opt.value ? 600 : 400 }}
                                >
                                  <span className={`w-1.5 h-1.5 rounded-full ${opt.dot}`} />
                                  {opt.label}
                                </button>
                              ))}
                            </div>
                          </div>
                          <div className="flex justify-end gap-2 pt-1">
                            <Button size="sm" variant="ghost" onClick={() => setEditingKeywordId(null)} className="text-gray-500">
                              Cancelar
                            </Button>
                            <Button
                              size="sm"
                              onClick={() => handleUpdateKeyword(kw.id)}
                              disabled={updateMutation.isPending || !editKwName.trim()}
                              className="bg-[#2a8c7a] hover:bg-[#244e47] text-white px-4 rounded-full"
                            >
                              {updateMutation.isPending ? <Loader2 size={12} className="animate-spin" /> : <Save size={12} />}
                              Guardar
                            </Button>
                          </div>
                        </div>
                      ) : (
                        /* ── Display card ─────────────────────────── */
                        <>
                          <div className="px-3.5 py-3 flex items-start gap-2.5 group">
                            {/* Expand chevron */}
                            {kw.is_active && (
                              <button
                                onClick={() => toggleKeywordExpand(kw.id)}
                                className="mt-0.5 p-0.5 rounded hover:bg-gray-100 text-gray-400 transition-colors shrink-0"
                              >
                                {expandedKeyword === kw.id
                                  ? <ChevronUp size={13} />
                                  : <ChevronDown size={13} />}
                              </button>
                            )}

                            {/* Content */}
                            <div
                              className="flex-1 min-w-0 cursor-pointer"
                              onClick={() => kw.is_active && toggleKeywordExpand(kw.id)}
                            >
                              <div className="flex items-center gap-2 flex-wrap">
                                <span className="text-sm text-gray-900" style={{ fontWeight: 500 }}>{kw.name}</span>
                                {kw.priority > 0 && (
                                  <span className="inline-flex items-center gap-1 text-[10px] px-1.5 py-0.5 rounded-full bg-gray-50 border border-gray-100 text-gray-500">
                                    <span className={`w-1.5 h-1.5 rounded-full ${pc.dot}`} />
                                    {pc.label}
                                  </span>
                                )}
                                {!kw.is_active && (
                                  <span className="text-[10px] text-red-500 bg-red-50 px-1.5 py-0.5 rounded-full">Eliminada</span>
                                )}
                              </div>
                              {kw.definition && (
                                <p className="text-xs text-gray-400 mt-1 leading-relaxed line-clamp-2">{kw.definition}</p>
                              )}
                            </div>

                            {/* Actions — always slightly visible */}
                            <div className="flex items-center gap-0.5 opacity-40 group-hover:opacity-100 transition-opacity shrink-0">
                              {kw.is_active ? (
                                <>
                                  <button
                                    onClick={() => {
                                      setEditingKeywordId(kw.id);
                                      setEditKwName(kw.name);
                                      setEditKwDef(kw.definition || '');
                                      setEditKwPriority(kw.priority);
                                      setShowNewKeyword(false);
                                    }}
                                    className="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400 hover:text-teal-600 transition-colors"
                                    title="Editar"
                                  >
                                    <Edit3 size={13} />
                                  </button>
                                  <button
                                    onClick={() => setDeletingKeywordId(kw.id)}
                                    className="p-1.5 rounded-lg hover:bg-red-50 text-gray-400 hover:text-red-500 transition-colors"
                                    title="Eliminar"
                                  >
                                    <Trash2 size={13} />
                                  </button>
                                </>
                              ) : (
                                <button
                                  onClick={() => restoreMutation.mutate(kw.id)}
                                  disabled={restoreMutation.isPending}
                                  className="p-1.5 rounded-lg hover:bg-emerald-50 text-gray-400 hover:text-emerald-600 transition-colors"
                                  title="Restaurar"
                                >
                                  {restoreMutation.isPending
                                    ? <Loader2 size={13} className="animate-spin" />
                                    : <RotateCcw size={13} />}
                                </button>
                              )}
                            </div>
                          </div>

                          {/* ── Subtopics (expanded) ──────────────── */}
                          <AnimatePresence>
                            {expandedKeyword === kw.id && kw.is_active && (
                              <motion.div
                                initial={{ height: 0, opacity: 0 }}
                                animate={{ height: 'auto', opacity: 1 }}
                                exit={{ height: 0, opacity: 0 }}
                                transition={{ duration: 0.15 }}
                                className="overflow-hidden"
                              >
                                <div className="border-t border-gray-100 bg-gray-50/60 px-4 py-3 pl-10">
                                  <div className="flex items-center gap-1.5 mb-2.5">
                                    <Layers size={11} className="text-gray-400" />
                                    <span className="text-[10px] text-gray-500 uppercase tracking-wider" style={{ fontWeight: 600 }}>
                                      Subtemas
                                    </span>
                                    <span className="text-[10px] text-gray-400">
                                      ({currentSubtopics.filter(s => s.is_active !== false).length})
                                    </span>
                                  </div>

                                  {subtopicsLoading ? (
                                    <div className="flex items-center gap-2 py-2">
                                      <Loader2 size={12} className="animate-spin text-gray-400" />
                                      <span className="text-xs text-gray-400">Cargando...</span>
                                    </div>
                                  ) : currentSubtopics.length === 0 ? (
                                    <p className="text-[11px] text-gray-400 py-1 italic">Sin subtemas aun</p>
                                  ) : (
                                    <div className="space-y-0.5 mb-2">
                                      {currentSubtopics.map(st => (
                                        <div
                                          key={st.id}
                                          className="flex items-center justify-between group/st py-1 px-2 -mx-2 rounded-md hover:bg-white/80 transition-colors"
                                        >
                                          <div className="flex items-center gap-2 min-w-0">
                                            <span className="w-1 h-1 rounded-full bg-gray-300 shrink-0" />
                                            <span className={`text-xs truncate ${st.is_active ? 'text-gray-600' : 'text-red-400 line-through'}`}>
                                              {st.name}
                                            </span>
                                          </div>
                                          {st.is_active && (
                                            <button
                                              onClick={() => handleDeleteSubtopic(st.id, kw.id)}
                                              className="p-0.5 rounded opacity-0 group-hover/st:opacity-100 hover:bg-red-50 text-gray-300 hover:text-red-400 transition-all shrink-0"
                                            >
                                              <X size={11} />
                                            </button>
                                          )}
                                        </div>
                                      ))}
                                    </div>
                                  )}

                                  {/* Add subtopic inline */}
                                  <div className="flex items-center gap-2 mt-2.5">
                                    <Input
                                      value={newSubtopicName}
                                      onChange={(e) => setNewSubtopicName(e.target.value)}
                                      placeholder="Agregar subtema..."
                                      className="h-7 text-xs bg-white"
                                      onKeyDown={(e) => {
                                        if (e.key === 'Enter') {
                                          e.preventDefault();
                                          handleCreateSubtopic(kw.id);
                                        }
                                      }}
                                    />
                                    <Button
                                      size="sm"
                                      variant="outline"
                                      className="h-7 px-2 shrink-0"
                                      disabled={createSubtopicMutation.isPending || !newSubtopicName.trim()}
                                      onClick={() => handleCreateSubtopic(kw.id)}
                                    >
                                      {createSubtopicMutation.isPending ? <Loader2 size={10} className="animate-spin" /> : <Plus size={10} />}
                                    </Button>
                                  </div>
                                </div>
                              </motion.div>
                            )}
                          </AnimatePresence>
                        </>
                      )}
                    </motion.div>
                  );
                })}
              </>
            )}
          </div>
        </SheetContent>
      </Sheet>

      {/* ═══════════════════════════════════════════════════ */}
      {/* VIDEOS SHEET (right side panel)                    */}
      {/* ═══════════════════════════════════════════════════ */}
      <Sheet open={showVideos} onOpenChange={setShowVideos}>
        <SheetContent className="w-[420px] sm:max-w-[420px] overflow-y-auto">
          <SheetHeader>
            <SheetTitle className="flex items-center gap-2">
              <VideoIcon size={16} className="text-blue-500" />
              Videos
            </SheetTitle>
          </SheetHeader>
          <div className="mt-4">
            <VideosManager summaryId={summary.id} onVideosChanged={(count: number) => setVideosCount(count)} />
          </div>
        </SheetContent>
      </Sheet>

      {/* Delete Keyword Confirmation */}
      <ConfirmDialog
        open={!!deletingKeywordId}
        onOpenChange={(open) => { if (!open) setDeletingKeywordId(null); }}
        title="Eliminar keyword"
        description="La keyword sera marcada como eliminada (soft-delete). Podras restaurarla despues."
        confirmLabel="Eliminar"
        variant="destructive"
        loading={deleteMutation.isPending}
        onConfirm={handleDeleteKeyword}
      />
    </div>
  );
}